In [1]:
import pandas as pd
import numpy as np

In [21]:
orders = pd.read_csv('../../orders.csv')
order_items = pd.read_csv('../../order_items.csv')
products = pd.read_csv('../../products.csv')
customers = pd.read_csv('../../customers.csv')

/var/folders/36/khn_y8zn7qqflczfpst8cbfc0000gn/T/ipykernel_28512/863286799.py:2: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  order_items = pd.read_csv('../../order_items.csv')

In [ ]:
orders_detail = orders.merge(order_items, on='order_id', how='left').merge(products, on='product_id', how='left').drop(columns=['price'])
orders_detail

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source,product_id,quantity,unit_price,discount_amount,promo_id,promo_id_2,product_name,category,segment,size,color,cogs
0,1,2012-07-04,58578,1109,delivered,credit_card,desktop,paid_search,2400,7,1138.22,0.0,NaN,NaN,VietMotion YY-09,GenZ,Trendy,S,red,1053.798008
1,2,2012-07-04,58621,1330,returned,cod,mobile,paid_search,609,7,10166.25,0.0,NaN,NaN,SaigonFlex UC-74,Streetwear,Everyday,M,yellow,8987.704231
2,3,2012-07-04,58811,1473,delivered,credit_card,desktop,direct,396,3,11220.33,0.0,NaN,NaN,SaigonFlex UM-01,Streetwear,Balanced,S,green,10091.012256
3,4,2012-07-04,59453,2360,delivered,credit_card,desktop,referral,635,5,10639.25,0.0,NaN,NaN,SaigonFlex UC-00,Streetwear,Everyday,XL,purple,9205.430478
4,6,2012-07-06,57821,2886,delivered,paypal,mobile,email_campaign,1935,1,1597.84,0.0,NaN,NaN,UrbanVN RP-10,Outdoor,Activewear,XL,purple,1048.696357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714664,834372,2022-12-31,19490,33907,delivered,credit_card,mobile,email_campaign,690,8,4473.92,0.0,NaN,NaN,SaigonFlex UC-55,Streetwear,Everyday,L,red,3100.062695
714665,834377,2022-12-31,73046,37091,delivered,credit_card,mobile,referral,1995,7,5250.79,0.0,NaN,NaN,UrbanVN UM-02,Streetwear,Balanced,XL,purple,3025.421056
714666,834387,2022-12-31,107723,80516,delivered,credit_card,mobile,email_campaign,2331,8,7389.06,0.0,NaN,NaN,VietMotion UE-05,Streetwear,Performance,XL,black,6671.816431
714667,834392,2022-12-31,139431,93510,delivered,paypal,desktop,direct,1115,5,4767.33,0.0,NaN,NaN,MekongFit RS-03,Outdoor,Premium,XL,purple,4587.478861
714668,834397,2022-12-31,136302,95678,delivered,credit_card,tablet,organic_search,1118,1,4716.75,0.0,NaN,NaN,MekongFit RS-06,Outdoor,Premium,L,pink,4323.853838

In [4]:
orders_detail.columns

Index(['order_id', 'order_date', 'customer_id', 'zip', 'order_status',
       'payment_method', 'device_type', 'order_source', 'product_id',
       'quantity', 'unit_price', 'discount_amount', 'promo_id', 'promo_id_2',
       'product_name', 'category', 'segment', 'size', 'color', 'cogs'],
      dtype='object')

In [5]:
orders_detail['total_revenue'] = orders_detail['quantity'] * orders_detail['unit_price']

In [6]:
orders_detail

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source,product_id,quantity,...,discount_amount,promo_id,promo_id_2,product_name,category,segment,size,color,cogs,total_revenue
0,1,2012-07-04,58578,1109,delivered,credit_card,desktop,paid_search,2400,7,...,0.0,NaN,NaN,VietMotion YY-09,GenZ,Trendy,S,red,1053.798008,7967.54
1,2,2012-07-04,58621,1330,returned,cod,mobile,paid_search,609,7,...,0.0,NaN,NaN,SaigonFlex UC-74,Streetwear,Everyday,M,yellow,8987.704231,71163.75
2,3,2012-07-04,58811,1473,delivered,credit_card,desktop,direct,396,3,...,0.0,NaN,NaN,SaigonFlex UM-01,Streetwear,Balanced,S,green,10091.012256,33660.99
3,4,2012-07-04,59453,2360,delivered,credit_card,desktop,referral,635,5,...,0.0,NaN,NaN,SaigonFlex UC-00,Streetwear,Everyday,XL,purple,9205.430478,53196.25
4,6,2012-07-06,57821,2886,delivered,paypal,mobile,email_campaign,1935,1,...,0.0,NaN,NaN,UrbanVN RP-10,Outdoor,Activewear,XL,purple,1048.696357,1597.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714664,834372,2022-12-31,19490,33907,delivered,credit_card,mobile,email_campaign,690,8,...,0.0,NaN,NaN,SaigonFlex UC-55,Streetwear,Everyday,L,red,3100.062695,35791.36
714665,834377,2022-12-31,73046,37091,delivered,credit_card,mobile,referral,1995,7,...,0.0,NaN,NaN,UrbanVN UM-02,Streetwear,Balanced,XL,purple,3025.421056,36755.53
714666,834387,2022-12-31,107723,80516,delivered,credit_card,mobile,email_campaign,2331,8,...,0.0,NaN,NaN,VietMotion UE-05,Streetwear,Performance,XL,black,6671.816431,59112.48
714667,834392,2022-12-31,139431,93510,delivered,paypal,desktop,direct,1115,5,...,0.0,NaN,NaN,MekongFit RS-03,Outdoor,Premium,XL,purple,4587.478861,23836.65
714668,834397,2022-12-31,136302,95678,delivered,credit_card,tablet,organic_search,1118,1,...,0.0,NaN,NaN,MekongFit RS-06,Outdoor,Premium,L,pink,4323.853838,4716.75

In [7]:
orders_detail['total_cogs'] = orders_detail['quantity'] * orders_detail['cogs']
orders_detail

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source,product_id,quantity,...,promo_id,promo_id_2,product_name,category,segment,size,color,cogs,total_revenue,total_cogs
0,1,2012-07-04,58578,1109,delivered,credit_card,desktop,paid_search,2400,7,...,NaN,NaN,VietMotion YY-09,GenZ,Trendy,S,red,1053.798008,7967.54,7376.586059
1,2,2012-07-04,58621,1330,returned,cod,mobile,paid_search,609,7,...,NaN,NaN,SaigonFlex UC-74,Streetwear,Everyday,M,yellow,8987.704231,71163.75,62913.929616
2,3,2012-07-04,58811,1473,delivered,credit_card,desktop,direct,396,3,...,NaN,NaN,SaigonFlex UM-01,Streetwear,Balanced,S,green,10091.012256,33660.99,30273.036767
3,4,2012-07-04,59453,2360,delivered,credit_card,desktop,referral,635,5,...,NaN,NaN,SaigonFlex UC-00,Streetwear,Everyday,XL,purple,9205.430478,53196.25,46027.152390
4,6,2012-07-06,57821,2886,delivered,paypal,mobile,email_campaign,1935,1,...,NaN,NaN,UrbanVN RP-10,Outdoor,Activewear,XL,purple,1048.696357,1597.84,1048.696357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714664,834372,2022-12-31,19490,33907,delivered,credit_card,mobile,email_campaign,690,8,...,NaN,NaN,SaigonFlex UC-55,Streetwear,Everyday,L,red,3100.062695,35791.36,24800.501564
714665,834377,2022-12-31,73046,37091,delivered,credit_card,mobile,referral,1995,7,...,NaN,NaN,UrbanVN UM-02,Streetwear,Balanced,XL,purple,3025.421056,36755.53,21177.947390
714666,834387,2022-12-31,107723,80516,delivered,credit_card,mobile,email_campaign,2331,8,...,NaN,NaN,VietMotion UE-05,Streetwear,Performance,XL,black,6671.816431,59112.48,53374.531451
714667,834392,2022-12-31,139431,93510,delivered,paypal,desktop,direct,1115,5,...,NaN,NaN,MekongFit RS-03,Outdoor,Premium,XL,purple,4587.478861,23836.65,22937.394304
714668,834397,2022-12-31,136302,95678,delivered,credit_card,tablet,organic_search,1118,1,...,NaN,NaN,MekongFit RS-06,Outdoor,Premium,L,pink,4323.853838,4716.75,4323.853838

In [8]:
orders_detail.drop(columns=['quantity', 'unit_price','cogs'], inplace=True)

In [9]:
orders_detail['order_date'] = pd.to_datetime(orders_detail['order_date'])

In [10]:
orders_detail

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source,product_id,discount_amount,promo_id,promo_id_2,product_name,category,segment,size,color,total_revenue,total_cogs
0,1,2012-07-04,58578,1109,delivered,credit_card,desktop,paid_search,2400,0.0,NaN,NaN,VietMotion YY-09,GenZ,Trendy,S,red,7967.54,7376.586059
1,2,2012-07-04,58621,1330,returned,cod,mobile,paid_search,609,0.0,NaN,NaN,SaigonFlex UC-74,Streetwear,Everyday,M,yellow,71163.75,62913.929616
2,3,2012-07-04,58811,1473,delivered,credit_card,desktop,direct,396,0.0,NaN,NaN,SaigonFlex UM-01,Streetwear,Balanced,S,green,33660.99,30273.036767
3,4,2012-07-04,59453,2360,delivered,credit_card,desktop,referral,635,0.0,NaN,NaN,SaigonFlex UC-00,Streetwear,Everyday,XL,purple,53196.25,46027.152390
4,6,2012-07-06,57821,2886,delivered,paypal,mobile,email_campaign,1935,0.0,NaN,NaN,UrbanVN RP-10,Outdoor,Activewear,XL,purple,1597.84,1048.696357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714664,834372,2022-12-31,19490,33907,delivered,credit_card,mobile,email_campaign,690,0.0,NaN,NaN,SaigonFlex UC-55,Streetwear,Everyday,L,red,35791.36,24800.501564
714665,834377,2022-12-31,73046,37091,delivered,credit_card,mobile,referral,1995,0.0,NaN,NaN,UrbanVN UM-02,Streetwear,Balanced,XL,purple,36755.53,21177.947390
714666,834387,2022-12-31,107723,80516,delivered,credit_card,mobile,email_campaign,2331,0.0,NaN,NaN,VietMotion UE-05,Streetwear,Performance,XL,black,59112.48,53374.531451
714667,834392,2022-12-31,139431,93510,delivered,paypal,desktop,direct,1115,0.0,NaN,NaN,MekongFit RS-03,Outdoor,Premium,XL,purple,23836.65,22937.394304
714668,834397,2022-12-31,136302,95678,delivered,credit_card,tablet,organic_search,1118,0.0,NaN,NaN,MekongFit RS-06,Outdoor,Premium,L,pink,4716.75,4323.853838

In [11]:
promotions = pd.read_csv('../../promotions.csv')
orders_detail = orders_detail.merge(
    promotions[['promo_id', 'discount_value']].rename(columns={'discount_value': 'dis_1'}),
    on='promo_id',
    how='left'
)
orders_detail.drop(columns=['promo_id'], inplace=True)
orders_detail

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source,product_id,discount_amount,promo_id_2,product_name,category,segment,size,color,total_revenue,total_cogs,dis_1
0,1,2012-07-04,58578,1109,delivered,credit_card,desktop,paid_search,2400,0.0,NaN,VietMotion YY-09,GenZ,Trendy,S,red,7967.54,7376.586059,NaN
1,2,2012-07-04,58621,1330,returned,cod,mobile,paid_search,609,0.0,NaN,SaigonFlex UC-74,Streetwear,Everyday,M,yellow,71163.75,62913.929616,NaN
2,3,2012-07-04,58811,1473,delivered,credit_card,desktop,direct,396,0.0,NaN,SaigonFlex UM-01,Streetwear,Balanced,S,green,33660.99,30273.036767,NaN
3,4,2012-07-04,59453,2360,delivered,credit_card,desktop,referral,635,0.0,NaN,SaigonFlex UC-00,Streetwear,Everyday,XL,purple,53196.25,46027.152390,NaN
4,6,2012-07-06,57821,2886,delivered,paypal,mobile,email_campaign,1935,0.0,NaN,UrbanVN RP-10,Outdoor,Activewear,XL,purple,1597.84,1048.696357,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714664,834372,2022-12-31,19490,33907,delivered,credit_card,mobile,email_campaign,690,0.0,NaN,SaigonFlex UC-55,Streetwear,Everyday,L,red,35791.36,24800.501564,NaN
714665,834377,2022-12-31,73046,37091,delivered,credit_card,mobile,referral,1995,0.0,NaN,UrbanVN UM-02,Streetwear,Balanced,XL,purple,36755.53,21177.947390,NaN
714666,834387,2022-12-31,107723,80516,delivered,credit_card,mobile,email_campaign,2331,0.0,NaN,VietMotion UE-05,Streetwear,Performance,XL,black,59112.48,53374.531451,NaN
714667,834392,2022-12-31,139431,93510,delivered,paypal,desktop,direct,1115,0.0,NaN,MekongFit RS-03,Outdoor,Premium,XL,purple,23836.65,22937.394304,NaN
714668,834397,2022-12-31,136302,95678,delivered,credit_card,tablet,organic_search,1118,0.0,NaN,MekongFit RS-06,Outdoor,Premium,L,pink,4716.75,4323.853838,NaN

In [12]:
orders_detail = orders_detail.merge(
    promotions[['promo_id', 'discount_value']].rename(columns={'discount_value': 'dis_2'}),
    left_on='promo_id_2',
    right_on='promo_id',
    how='left'
)
orders_detail.drop(columns=['promo_id_2','promo_id'], inplace=True)
orders_detail

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source,product_id,discount_amount,product_name,category,segment,size,color,total_revenue,total_cogs,dis_1,dis_2
0,1,2012-07-04,58578,1109,delivered,credit_card,desktop,paid_search,2400,0.0,VietMotion YY-09,GenZ,Trendy,S,red,7967.54,7376.586059,NaN,NaN
1,2,2012-07-04,58621,1330,returned,cod,mobile,paid_search,609,0.0,SaigonFlex UC-74,Streetwear,Everyday,M,yellow,71163.75,62913.929616,NaN,NaN
2,3,2012-07-04,58811,1473,delivered,credit_card,desktop,direct,396,0.0,SaigonFlex UM-01,Streetwear,Balanced,S,green,33660.99,30273.036767,NaN,NaN
3,4,2012-07-04,59453,2360,delivered,credit_card,desktop,referral,635,0.0,SaigonFlex UC-00,Streetwear,Everyday,XL,purple,53196.25,46027.152390,NaN,NaN
4,6,2012-07-06,57821,2886,delivered,paypal,mobile,email_campaign,1935,0.0,UrbanVN RP-10,Outdoor,Activewear,XL,purple,1597.84,1048.696357,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714664,834372,2022-12-31,19490,33907,delivered,credit_card,mobile,email_campaign,690,0.0,SaigonFlex UC-55,Streetwear,Everyday,L,red,35791.36,24800.501564,NaN,NaN
714665,834377,2022-12-31,73046,37091,delivered,credit_card,mobile,referral,1995,0.0,UrbanVN UM-02,Streetwear,Balanced,XL,purple,36755.53,21177.947390,NaN,NaN
714666,834387,2022-12-31,107723,80516,delivered,credit_card,mobile,email_campaign,2331,0.0,VietMotion UE-05,Streetwear,Performance,XL,black,59112.48,53374.531451,NaN,NaN
714667,834392,2022-12-31,139431,93510,delivered,paypal,desktop,direct,1115,0.0,MekongFit RS-03,Outdoor,Premium,XL,purple,23836.65,22937.394304,NaN,NaN
714668,834397,2022-12-31,136302,95678,delivered,credit_card,tablet,organic_search,1118,0.0,MekongFit RS-06,Outdoor,Premium,L,pink,4716.75,4323.853838,NaN,NaN

In [ ]:
orders_detail = orders_detail.merge(customers[['customer_id', 'city']], on='customer_id', how='left').drop(columns=['customer_id'])
orders_detail

,order_id,order_date,zip,order_status,payment_method,device_type,order_source,product_id,discount_amount,product_name,category,segment,size,color,total_revenue,total_cogs,dis_1,dis_2,city
0,1,2012-07-04,1109,delivered,credit_card,desktop,paid_search,2400,0.0,VietMotion YY-09,GenZ,Trendy,S,red,7967.54,7376.586059,0.0,0.0,Hanoi
1,2,2012-07-04,1330,returned,cod,mobile,paid_search,609,0.0,SaigonFlex UC-74,Streetwear,Everyday,M,yellow,71163.75,62913.929616,0.0,0.0,Phu Ly
2,3,2012-07-04,1473,delivered,credit_card,desktop,direct,396,0.0,SaigonFlex UM-01,Streetwear,Balanced,S,green,33660.99,30273.036767,0.0,0.0,Lao Cai
3,4,2012-07-04,2360,delivered,credit_card,desktop,referral,635,0.0,SaigonFlex UC-00,Streetwear,Everyday,XL,purple,53196.25,46027.152390,0.0,0.0,Son Tay
4,6,2012-07-06,2886,delivered,paypal,mobile,email_campaign,1935,0.0,UrbanVN RP-10,Outdoor,Activewear,XL,purple,1597.84,1048.696357,0.0,0.0,Uong Bi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714664,834372,2022-12-31,33907,delivered,credit_card,mobile,email_campaign,690,0.0,SaigonFlex UC-55,Streetwear,Everyday,L,red,35791.36,24800.501564,0.0,0.0,Bac Ninh
714665,834377,2022-12-31,37091,delivered,credit_card,mobile,referral,1995,0.0,UrbanVN UM-02,Streetwear,Balanced,XL,purple,36755.53,21177.947390,0.0,0.0,Ha Long
714666,834387,2022-12-31,80516,delivered,credit_card,mobile,email_campaign,2331,0.0,VietMotion UE-05,Streetwear,Performance,XL,black,59112.48,53374.531451,0.0,0.0,Kon Tum
714667,834392,2022-12-31,93510,delivered,paypal,desktop,direct,1115,0.0,MekongFit RS-03,Outdoor,Premium,XL,purple,23836.65,22937.394304,0.0,0.0,Ben Tre
714668,834397,2022-12-31,95678,delivered,credit_card,tablet,organic_search,1118,0.0,MekongFit RS-06,Outdoor,Premium,L,pink,4716.75,4323.853838,0.0,0.0,Bac Lieu

In [13]:
orders_detail['dis_1'] = orders_detail['dis_1'].fillna(0)
orders_detail['dis_2'] = orders_detail['dis_2'].fillna(0)

In [26]:
df = orders_detail.groupby(['order_date','segment','category','order_source','dis_1','dis_2', 'city'])['total_revenue'].sum().reset_index()
df['total_cogs'] = orders_detail.groupby(['order_date','segment','category','order_source','dis_1','dis_2', 'city'])['total_cogs'].sum().values

In [27]:
df

,order_date,segment,category,order_source,dis_1,dis_2,city,total_revenue,total_cogs
0,2012-07-04,Activewear,Outdoor,direct,0.0,0.0,Can Tho,13254.31,10205.253388
1,2012-07-04,Activewear,Outdoor,direct,0.0,0.0,Da Nang,1641.85,1337.836464
2,2012-07-04,Activewear,Outdoor,direct,0.0,0.0,Hai Phong,8995.77,8130.592301
3,2012-07-04,Activewear,Outdoor,email_campaign,0.0,0.0,Bac Giang,3326.75,3288.465833
4,2012-07-04,Activewear,Outdoor,email_campaign,0.0,0.0,Can Tho,12589.92,9113.723304
...,...,...,...,...,...,...,...,...,...
572686,2022-12-31,Premium,Outdoor,social_media,20.0,0.0,Bien Hoa,13093.00,15944.774009
572687,2022-12-31,Premium,Outdoor,social_media,20.0,0.0,Da Nang,12423.60,13178.149398
572688,2022-12-31,Standard,Streetwear,social_media,20.0,0.0,Vinh Long,12797.73,12043.796062
572689,2022-12-31,Trendy,GenZ,email_campaign,0.0,0.0,Ninh Binh,13738.50,12917.126250
572690,2022-12-31,Trendy,GenZ,paid_search,20.0,0.0,Tam Ky,7136.15,8374.810500

In [28]:
df[df['order_date'] == '2012-07-04']['total_revenue'].sum()

np.float64(5123547.9399999995)

In [30]:
df.to_csv('data.csv', index=False)